######################################################################
# Automatically generated by qmake (3.1) Thu Jul 20 15:56:11 2017
######################################################################

TEMPLATE = app
TARGET = test-v8-csvFile
INCLUDEPATH += .
QT += opengl

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
