######################################################################
# Automatically generated by qmake (3.1) Fri Jul 14 11:48:36 2017
######################################################################

TEMPLATE = app
TARGET = test-v3-file-dialog
INCLUDEPATH += .
QT+=opengl
# Input
SOURCES += main.cpp
