######################################################################
# Automatically generated by qmake (3.1) Mon Jul 17 10:24:59 2017
######################################################################

TEMPLATE = app
TARGET = test-v4-draw
INCLUDEPATH += .
QT+=opengl

# Input
HEADERS += mywidget.h
SOURCES += main.cpp mywidget.cpp
