######################################################################
# Automatically generated by qmake (3.1) Wed Aug 2 09:17:03 2017
######################################################################

TEMPLATE = app
TARGET = test-v9-menubar
INCLUDEPATH += .
QT += opengl

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
