######################################################################
# Automatically generated by qmake (3.1) Thu Jul 20 11:56:58 2017
######################################################################

TEMPLATE = app
TARGET = test-v7-plot
INCLUDEPATH += .
QT += widgets printsupport

# Input
HEADERS += mainwindow.h qcustomplot.h
SOURCES += main.cpp mainwindow.cpp qcustomplot.cpp
