######################################################################
# Automatically generated by qmake (3.1) Fri Jul 21 16:48:20 2017
######################################################################

TEMPLATE = app
TARGET = test-v6-qvector
INCLUDEPATH += .
QT += opengl
QT += widgets printsupport
CONFIG += link_pkgconfig
PKGCONFIG += opencv
#CONFIG(release, debug|release):DEFINES += QT_NO_DEBUG_OUTPUT



# Input
HEADERS += dialog.h \
           qcustomplot.h \
           include/alignment.h \
           include/feature.h \
           include/utility.h
SOURCES += dialog.cpp \
           main.cpp \
           qcustomplot.cpp \
           lib/alignment.cpp \
           lib/feature.cpp \
           lib/utility.cpp
