######################################################################
# Automatically generated by qmake (3.1) Wed Aug 2 17:01:52 2017
######################################################################

TEMPLATE = app
TARGET = test-v10-table
INCLUDEPATH += .
QT+=opengl

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
