######################################################################
# Automatically generated by qmake (3.1) Thu Jul 13 14:16:14 2017
######################################################################

TEMPLATE = app
TARGET = test-v0
INCLUDEPATH += .
QT+=opengl
# Input
SOURCES += qt-test.cpp
