######################################################################
# Automatically generated by qmake (3.1) Fri Jul 14 09:34:26 2017
######################################################################

TEMPLATE = app
TARGET = test-v0
INCLUDEPATH += .
QT+=opengl
# Input
SOURCES += qt-test.cpp test-v0_plugin_import.cpp
