######################################################################
# Automatically generated by qmake (3.1) Fri Jul 14 15:48:14 2017
######################################################################

TEMPLATE = app
TARGET = test-v2-fileBrowser
INCLUDEPATH += .
QT+=opengl
#CONFIG(release, debug|release):DEFINES += QT_NO_DEBUG_OUTPUT

# Input
HEADERS += dialog.h
SOURCES += dialog.cpp main.cpp
